defaults: ./grpo-nemotron-super-20n8g-gym.yaml

checkpointing:
  checkpoint_dir: results/grpo-nemotron-super-36n4g-gym

logger:
  wandb:
    name: ananthsub-grpo-nemotron-super-36n4g-gym-gb200-hsg
    run_name: grpo-nemotron-super-36n4g-gym

policy:
  generation:
    colocated:
      enabled: false
      resources:
        num_nodes: 16
        gpus_per_node: 4
env:
  nemo_gym:
    nl2bash_judge_model:
      responses_api_models:
        vllm_model:
          router_dp_size: 1

cluster:
  gpus_per_node: 4
  num_nodes: 36
