defaults: ./grpo-nanov3-30ba3b-1n4g-megatron-mxfp8-convergence.yaml
grpo:
  max_num_steps: 2
policy:
  megatron_cfg:
    train_iters: 2
    optimizer:
      lr: 0.0
      min_lr: 0.0
      weight_decay: 0.0
    scheduler:
      start_weight_decay: 0.0
      end_weight_decay: 0.0
      lr_warmup_init: 0.0
