defaults: ./grpo-qwen3-32b-8n4g-async-1off.yaml
checkpointing:
  checkpoint_dir: results/grpo-qwen3-32b-8n4g-async-1off-mxfp8-rollout
policy:
  generation:
    vllm_cfg:
      async_engine: true
      tensor_parallel_size: 1
      gpu_memory_utilization: 0.8
      precision: "fp8"
      is_mx: true
      quantization_ignore_patterns:
        - model.layers.*.self_attn.*
        - lm_head
    vllm_kwargs:
      moe_backend: flashinfer_trtllm
logger:
  log_dir: logs/grpo-qwen3-32b-8n4g-async-1off-mxfp8-rollout
  wandb:
    name: grpo-qwen3-32b-8n4g-async-1off-mxfp8-rollout
cluster:
  gpus_per_node: 4
  num_nodes: 8
  segment_size: 4
