defaults: ./grpo-qwen3-235b-16n4g.yaml
checkpointing:
  checkpoint_dir: results/grpo-qwen3-235b-16n4g-mxfp8-rollout
policy:
  generation:
    vllm_cfg:
      tensor_parallel_size: 4
      precision: "fp8"
      is_mx: true
      quantization_ignore_patterns:
        - model.layers.*.self_attn.*
        - model.layers.*.mlp.gate
        - lm_head
    vllm_kwargs:
      moe_backend: flashinfer_trtllm
logger:
  log_dir: logs/grpo-qwen3-235b-16n4g-mxfp8-rollout
  wandb:
    name: grpo-qwen3-235b-16n4g-mxfp8-rollout
cluster:
  segment_size: 16
